company/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login$', views.login, name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^home$', views.index, name='home'),
    url(r'^games/(?P<pag>\d+)$', views.games, name='games'),
    url(r'^news/(?P<pag>\d+)$', views.news, name='news'),
    url(r'^business$', views.business, name='business'),
    url(r'^joinUs$', views.joinUs, name='joinUs'),
    url(r'^aboutUs$', views.aboutUs, name='aboutUs'),
    url(r'^gameDetail/(?P<game_index>\d+)$', views.gameDetail, name='gameDetail'),
    url(r'^newsDetail/(?P<new_id>\d+)$', views.newsDetail, name='newsDetail'),
    url(r'^jobDesc/(?P<job_id>\d+)$', views.jobDesc, name='jobDesc'),
]

honvue_pag/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [ 
    url(r'', include('company.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

#urlpatterns += [
#    (r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico')),
#]

company/models.py
#-*- coding: utf8 -*-

import re
import time
import hashlib
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

RBLANK = re.compile(r'\s+')
ADDCODE = "hy"


@python_2_unicode_compatible  # only if you need to support Python 2
class HyMember(models.Model):
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    member_id = models.CharField(max_length=200)
    session_expired_time = models.IntegerField() 

    def __str__(self):
        return self.username
    
    @classmethod
    def create_new_user(cls, username, password): 
        obj = cls()
        obj.username = username
        obj.password = obj.dim_password(password) 
        member_id = username + hashlib.md5(username + str(int(time.time()))).hexdigest() 
        obj.session_expired_time = int(time.time()) + 10 * 24 * 3600
        obj.save()
        return obj
    
    def dim_password(self, password):
        return hashlib.md5(password + ADDCODE).hexdigest()


# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
# 
# 
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)


@python_2_unicode_compatible  # only if you need to support Python 2
class Game(models.Model):
    index = models.IntegerField()
    name = models.CharField(max_length=200)
    bigpicture = models.CharField(max_length=200)
    smpicture = models.CharField(max_length=200)
    showpictures = models.CharField(max_length=200)
    small_desc = models.CharField(max_length=1000)
    main_desc = models.TextField(max_length=20000)
    feature_desc = models.TextField(max_length=20000)
    type_tags = models.CharField(max_length=200)
    IOS_link = models.CharField(max_length=100, default=None, blank=True, null=True)
    ANDROID_link = models.CharField(max_length=100, default=None, blank=True, null=True)

    def __str__(self):
        return self.name
    
    def get_showpictures(self):
        return RBLANK.split(self.showpictures)
    
    def get_type_tags(self):
        return RBLANK.split(self.type_tags)


@python_2_unicode_compatible  # only if you need to support Python 2
class New(models.Model):
    title = models.CharField(max_length=200)
    bigpicture = models.CharField(max_length=200)
    smpicture = models.CharField(max_length=200)
    content = models.TextField(max_length=20000)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title


@python_2_unicode_compatible  # only if you need to support Python 2
class JobCategory(models.Model):
    index = models.IntegerField()
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


@python_2_unicode_compatible  # only if you need to support Python 2
class Job(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField(max_length=20000)
    category = models.ForeignKey(JobCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

company/views.py
# -*- coding: utf-8 -*-
import json
from django.shortcuts import render
from django.http import HttpResponse
# from django.http import HttpResponseRedirect
from . import configs
from .models import Game, New, JobCategory, Job, HyMember
from django.http import Http404
from django.shortcuts import get_object_or_404


def login(request):
    info = {
        'flag': False,
        'username': '',
        'errmsg': '',
    }
    try:
        m = HyMember.objects.get(username=str(request.POST['username']))
    except:
        info['errmsg'] =  u"用户名不存在"
    else:
        if m.password != m.dim_password(request.POST['password']):
            info['errmsg'] = u"密码不正确"
        else:
            request.session['member_id'] = m.member_id
            info['flag'] = True
            info['username'] = m.username
    return HttpResponse(json.dumps(info))
    

def register(request): 
    info = {
        'flag': False,
        'username': '',
        'errormsg': '',
    }
    try:
        username = str(request.POST['username'])
    except UnicodeEncodeError:
        info['errmsg'] = u'用户名必须由字母和数字组成'
        return HttpResponse(json.dumps(info))
    try:
        pw = str(request.POST['password']) 
    except UnicodeEncodeError:
        info['errmsg'] = u'密码必须由字母数字符号组成'
        return HttpResponse(json.dumps(info))
    # 密码不为空
    if pw == '':
        info['errmsg'] = u'密码不能为空'
        return HttpResponse(json.dumps(info))
    try:
        m = HyMember.objects.get(username=username)
    except:
        m = HyMember.create_new_user(username, pw)
        info['flag'] = True
        info['username'] = m.username
        request.session['member_id'] = m.member_id
    else:
        info['errmsg'] =  u"用户名已存在"
    return HttpResponse(json.dumps(info))


def index(request):
    return home(request)


def home(request):
    games = Game.objects.order_by('index')
    context = {'games': games, 'toptag': 'home'}
    return render(request, 'home.html', context)

def games(request, pag=1):
    gap = 3
    pag = int(pag)
    all_games = Game.objects.order_by('index') 
    games = all_games[(pag -1)*gap:gap*pag]
    total_pags = range(1, ((len(all_games) - 1) // gap + 2))
    pre_pag = (pag - 1) if pag > 1 else 1
    next_pag = (pag + 1) if pag < total_pags[-1] else total_pags[-1]
    context = {'toptag': 'games', 'games': games, 'pag': pag, 'total_pags': total_pags, 'pre_pag': pre_pag, 'next_pag': next_pag}
    return render(request, 'games.html', context)

def news(request, pag=1):
    gap = 3 
    pag = int(pag)
    all_news = New.objects.order_by('-pub_date')
    news = all_news[(pag -1)*gap: gap*pag]
    total_pags = range(1, ((len(all_news) - 1) // gap + 2))
    pre_pag = (pag - 1) if pag > 1 else 1
    next_pag = (pag + 1) if pag < total_pags[-1] else total_pags[-1]
    context = {'toptag': 'news', 'news': news, 'pag': pag, 'total_pags': total_pags, 'pre_pag': pre_pag, 'next_pag': next_pag}

    return render(request, 'news.html', context)

def business(request):
    context = {'toptag': 'business'}
    return render(request, 'business.html', context)

def joinUs(request):
    categorys = JobCategory.objects.order_by('index')
    context = {'toptag': 'joinUs', 'categorys': categorys}
    return render(request, 'joinUs.html', context)

def aboutUs(request):
    context = {'toptag': 'aboutUs'}
    return render(request, 'aboutUs.html', context)

def gameDetail(request, game_index):
    game_index = int(game_index) 
    game = get_object_or_404(Game, index=game_index)
    context = {'toptag': 'games', 'game': game}
    return render(request, 'gameDetail.html', context)

def newsDetail(request, new_id):
    new_id = int(new_id) 
    new = get_object_or_404(New, id=new_id)
    context = {'toptag': 'news', 'new': new}
    return render(request, 'newsDetail.html', context)

def jobDesc(request, job_id):
    try:
        job = get_object_or_404(Job, id=job_id)
    except IndexError:
        raise Http404("Job does not exist")
    return HttpResponse(job.desc.lstrip())

templates/aboutUs.html
{% extends "base.html" %}
{% block content %}
{% load static %}


<div class="container">
    <div  style="margin-top: 70px;margin-bottom: 50px;">
        <p style="text-align: left">
            <span style="font-size: 36px ;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #000000;font-weight: 700">
                关于我们
            </span>
            <span style="margin-left: 10px;font-size: 24px;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #999999;font-weight: 700">
                ABOUT US
            </span>
        </p>

    </div>


    <div class="row" style="width: 100%;text-align: center;" align="center">
        <div class="col-xs-4 col-md-4" >
            <div class="thumbnail">
                <img src="{% static '/images/aboutus4.jpg' %}" alt="">
            </div>
        </div>

        <div class="col-xs-4 col-md-4">
            <div class="thumbnail">
                <img src="{% static '/images/aboutus1.jpg' %}" alt="">
            </div>
        </div>

        <div class="col-xs-4 col-md-4" >
            <div class="thumbnail">
                <img src="{% static '/images/aboutus.jpg' %}" alt="">
            </div>
        </div>
        <!--
        <div class="col-xs-7 col-md-7 col-xs-offset-2">
            <div class="thumbnail">
                <img src="/images/aboutus4.jpg" alt="">
            </div>
        </div>
        -->
    </div>


    <div style="margin-top: 50px;margin-bottom: 100px;width: 80%;margin-left: 10%">
        <p style="white-space: normal;font-size: 24px;font-family: '微软雅黑 Regular', '微软雅黑'">
            <span>
               洪禹科技(上海)有限公司(总部位于中国上海)是一家业内领先的手机游戏研发和运营商，为游戏发行商和用户提供最优质服务。<br><br>
            </span>
        </p>

        <p style="white-space: normal;font-size: 24px;font-family: '微软雅黑 Regular', '微软雅黑'">
            <span>
               公司一支具有全球化视野和专业化技能的团队，所有成员均有多年的游戏行业经验，以及不少于2款大型成功游戏的研发与运营经验。<br><br>
            </span>
        </p>

        <p style="white-space: normal;font-size: 24px;font-family: '微软雅黑 Regular', '微软雅黑'">
            <span>
               公司以“为全球玩家创造最好的游戏娱乐生活”为发展目标，致力于为中国乃至全球的玩家提供最优质的游戏服务。目前公司的新款游戏产品已进入研发阶段，我们将继续努力，为游戏行业和广大玩家带来更多的创新与惊喜。
            </span>
        </p>



    </div>


</div>
{% endblock %}

templates/business.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=8vIE7dgAVgXvYgEqGpyAb7Y9"></script>
<script type="text/javascript" src="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.js"></script>
<link rel="stylesheet" href="http://api.map.baidu.com/library/SearchInfoWindow/1.5/src/SearchInfoWindow_min.css" />

<script type="text/javascript">
    var data=0;
    var slideFlag=false;
    var putFlag=false;
    // 百度地图API功能
    var map = new BMap.Map("l-map");            // 创建Map实例
    map.centerAndZoom(new BMap.Point(116.404, 39.915), 11);
    var local = new BMap.LocalSearch(map, {
        renderOptions: {map: map, panel: "r-result"}
    });
    local.search("餐饮");
</script>






<div class="container">

    <div  style="margin-top: 70px;margin-bottom: 30px;">
        <p style="text-align: left">
            <span style="font-size: 36px ;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #000000;font-weight: 700">
                商务洽谈
            </span>
            <span style="margin-left: 10px;font-size: 24px;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #999999;font-weight: 700">
                BUSINESS
            </span>
        </p>

        <br><br>
        <p >
        <div style="background: #029aff;width: 28px;height: 28px;float: left;margin-right: 30px;"></div> <span class="mes" > 商务洽谈邮箱：info@honvue.com</span>

        </p>
        <br><br>

        <p >
        <div style="background: #029aff;width: 28px;height: 28px;float: left;margin-right: 30px;"></div> <span class="mes">人才招聘：hr@honvue.com</span>
        </p>
        <br><br>
        <p >
        <div style="background: #029aff;width: 28px;height: 28px;float: left;margin-right: 30px;"></div><span class="mes">玩家反馈邮箱：feedback@honvue.com</span>
        </p>



    </div>

    <div style="float: left;width: 100%;border-bottom: 1px solid #9a9a9a;margin-top: 40px;">

    </div>

    <div  style="margin-top: 120px;margin-bottom: 30px;">
        <p style="text-align: left">
            <span style="font-size: 36px ;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #000000;font-weight: 700">
                办公地点
            </span>
            <span style="margin-left: 10px;font-size: 24px;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #999999;font-weight: 700">
               ADDRESS
            </span>
        </p>
    </div>

    <div>

        <div style="display: block;float: left ;width: 100%">



            <div style="margin-bottom: 150px;margin-top: 50px;margin-left: 20px;width: 60%;float: left;">
                <p style="display: inline">

                    <img src="{% static '/images/map.png' %}" style="width: 33px;height: 35px;margin-top: -5px;margin-right: 15px"><span style="line-height: 30px;font-family: '微软雅黑 Regular', '微软雅黑';font-size: 24px;">地址：上海市黄浦区北京东路668号科技京城东楼24层H2</span>


                </p>

                <p style="display: block;margin-top: 20px;">
                    <img src="{% static '/images/phone.png' %}" style="width: 33px;height: 35px;margin-top: -5px;margin-right: 15px">
                    <span style="line-height: 30px;font-family: '微软雅黑 Regular', '微软雅黑';font-size: 24px;">电话：021-68543816</span>
                </p>

            </div>

            <div style="display: block;margin-top: 0px;float: right;width: 20%;margin-right: -30px;">
                <img src="{% static '/images/hyew.jpg' %}" style="width: 83%;border: solid #e6e6e6 1px">
            </div>



        </div>


        <div id="allmap" style="height: 300px;width: 100%;margin-top: -90px;display: block;width: 100%;float: left"></div>






        



        <script type="text/javascript">

            // 百度地图API功能
            var map = new BMap.Map('allmap');
            var poi = new BMap.Point(121.485967,31.245441);
            map.centerAndZoom(poi, 16);
            map.enableScrollWheelZoom();

            var content = '<div style="margin:0;line-height:20px;padding:2px;">' +
                    '地址：黄浦区北京东路668号科技京城东楼24层H2' +
                    '</div>';

            //创建检索信息窗口对象
            var searchInfoWindow = null;
            searchInfoWindow = new BMapLib.SearchInfoWindow(map, content, {
                title  : "洪禹科技",      //标题
                width  : 290,             //宽度
                height : 30,              //高度
                panel  : "panel",         //检索结果面板
                enableAutoPan : true,     //自动平移
                searchTypes   :[
                    BMAPLIB_TAB_SEARCH,   //周边检索
                    BMAPLIB_TAB_TO_HERE,  //到这里去
                    BMAPLIB_TAB_FROM_HERE //从这里出发
                ]
            });
            var marker = new BMap.Marker(poi); //创建marker对象
            marker.enableDragging(); //marker可拖拽
            marker.addEventListener("click", function(e){
                searchInfoWindow.open(marker);
            })
            map.addOverlay(marker); //在地图中添加marker


            $(document).ready(function() {
                searchInfoWindow.open(marker);
            });
        </script>

    </div>



</div>







</div>






{% endblock %}

templates/footer.html

<div class="footer" style="bottom: 0;position: fixed;width: 100%">
    <div class="container" style="text-align: center">

        <p><span>Copyright © Honvue Technology (shanghai) Co., Ltd All Right Reserved.</span></p>
        <p><span >洪禹科技(上海)有限公司 版权所有</span></p>
        <p><span>互联网(ICP许可证):沪ICP备15034113号</span></p>

    </div>
</div>


templates/gameDetail.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <div style="text-align: center;margin-top: 5%">
        <p>
            <span style="text-align: center ;font-size: 36px;font-family: '微软雅黑 Bold', 微软雅黑">
                {{ game.name }}
            </span>
        </p>
    </div>

    <div>
        <div style="text-align: left">
            <p>
                <span  style="text-align: center ;font-size: 24px;font-family: '微软雅黑 Regular', 微软雅黑">
                    游戏简介
                </span>
            </p>

            <p>
                <pre class="preword">{{ game.main_desc }}</pre>
            </p>

        </div>
        <!-- 游戏截图 -->
        <div style="margin-top: 50px;margin-bottom: 50px;">
            <p>
                <span  style="text-align: center ;font-size: 24px;font-family: '微软雅黑 Regular', 微软雅黑">
                    游戏截图
                </span>
            </p>

            <div class="row" style="width: 100%;text-align: center;" align="center">
                {% for showpicture in game.get_showpictures|slice:":3" %}
                <div class="col-sm-6 col-md-4" >
                    <div class="thumbnail">
                        <img src="{% static '/images/' %}{{ showpicture }}" alt="">
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>


        <div style="text-align: left;margin-bottom: 200px;">
            <p>
                <span  style="text-align: center ;font-size: 24px;font-family: '微软雅黑 Regular', 微软雅黑">
                    游戏特色
                </span>
            </p>
            <p>
            <pre class="preword">{{ game.feature_desc }}</pre>
            </p>
        </div>
    </div>

</div>
{% endblock %}

templates/header.html
{% load static %}
<script>
    function select(url,id){
        var ids="#"+id;
        $("#main").load(url);
        $(ids).css({"background-color":'#0099ff',"opacity":"1"});
        var array= $("#ulId").children().children();
        $.each(array,function(i,value){
            var idValue=$(value).attr('id');
            var idValues="#"+idValue;
            if(idValue!=id){
                $(idValues).css({"background-color":'#333333',"opacity":"0.7"});
                $(idValues).mouseover(function(e){
                    $(idValues).css("opacity","1");
                });
                $(idValues).mouseleave(function(e){
                    $(idValues).css("opacity","0.7");
                });
            }else{
                $(idValues).css("opacity","1");
                $(idValues).mouseover(function(e){
                    $(idValues).css("opacity","1");
                });
                $(idValues).mouseleave(function(e){
                    $(idValues).css("opacity","1");
                });
            }
        });
    }

</script>
<div class="header" id="homea">
    <div class="header_nav" id="home">
        <nav class="navbar navbar-default chn-gd">
            <div class="container">
                <div class="navbar-header" style="margin-left: -6%">
                    <div id="u35"><img id="u35_img" class="img" src="{% static '/images/logo1.png' %}"></div>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right" style="margin-right: -2%" id="ulId">
                        <li >
                            <a id="hy" onclick="select('index.html','hy');">
                                <div class="navtitle">
                                    洪禹科技<br>
                                    <div>HOME</div>
                                </div>

                            </a>
                        </li>
                        <!---->
                        <li>
                            <a id="game" onclick="select('games.html','game');">
                                <div class="navtitle">
                                    游戏产品<br>
                                    <div> GAMES</div>
                                </div>
                            </a>
                        </li>
                        <!---->
                        <li>
                            <a id="new" onclick="select('news.html','new');">
                                <div class="navtitle">
                                    公司动态<br>
                                    <div> NEWS</div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a id="business" onclick="select('business.html','business');">
                                <div class="navtitle">
                                    商务洽谈<br>
                                    <div>BUSINESS</div>
                                </div>
                            </a>
                        </li>

                        <li>
                            <a id="ju" onclick="select('joinUs.html','ju');" >
                                <div class="navtitle">
                                    加入我们<br>
                                    <div>JOIN US</div>
                                </div>
                            </a>
                        </li>

                        <li>

                            <a id="about" onclick="select('aboutUs.html','about');">
                                <div class="navtitle">
                                    关于我们<br>
                                    <div>ABOUT US</div>
                                </div>
                            </a>
                        </li>

                    </ul>
                </div>

            </div>
        </nav>
    </div>

</div>

templates/joinUs.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<style>

    .zhiwei{
        font-size: 24px ;
        font-family: '微软雅黑 Bold', 微软雅黑 ;
        color: #000000;
        font-weight: 700;
    }

    .zizhiwei{
        color:#000000;
        font-size: 18px;
        font-weight: 400;
        font-family: '微软雅黑 Regular', '微软雅黑';
        cursor:pointer;
    }


</style>


<script type="text/javascript">
    function choosework(url, job_id){
        var ids="#job"+job_id;
        var job_name = $(ids).html();
        //根据请求路径获取对应的返回
        $("#job_name").html(job_name.substring(4));
        $.ajax({
            type:"GET",
            url:url,
            isRefToken:false,
            success: function(res) {
                $("#workDetail").html(res);
                $(".zizhiwei").css("color","black");
                $(ids).css("color", "#0099ff");
            }
        });
    }
    $(document).ready(function() {
        var first_job = $(".zizhiweiname:first");
        first_job.click();
    });
</script>


<div class="container">
    <div  style="margin-top: 70px;margin-bottom: 50px;">
        <p style="text-align: left">
            <span style="font-size: 36px ;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #000000;font-weight: 700">
                加入我们
            </span>
            <span style="margin-left: 10px;font-size: 24px;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #999999;font-weight: 700">
                JOIN US
            </span>
        </p>

        <div style="margin-top: 40px;margin-bottom: 50px">
            <p style="text-align: left">
            <span style="color:#333333;font-size: 24px;font-weight: 400;font-family: '微软雅黑 Regular', '微软雅黑';line-height: 30px;">
                招精英人才，做精品游戏。洪禹科技，期待您的加入。
            </span>
            </p>
            <p style="text-align: left;margin-top: -10px" >
            <span style="color:#333333;font-size: 24px;font-weight: 400;font-family: '微软雅黑 Regular', '微软雅黑';line-height: 60px;">
                简历请发送到邮箱：<span style="color:#0099FF;">hr@honvue.com</span>
            </span>
            </p>

        </div>

    </div>



    <div style="width: 140%;border-bottom: 1px solid rgba(98, 89, 93, 0.51);margin-left: -20%; "></div>

    <div style="margin-top: 60px">
        <div>
            <p style="text-align: left">
            <span style="font-size: 36px ;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #000000;font-weight: 700">
                职能分类
            </span>
            <span style="margin-left: 10px;font-size: 24px;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #999999;font-weight: 700">
                POSITION TYPE
            </span>
            </p>
        </div>


        <div  style="margin-top: 0px">

            <table style="width: 100%">
                <tr style="width: 100%;" >
                    <td style="border-right: 1px solid #000000;text-align: left; vertical-align: top;width: 40%">
                        <!-- 分类 -->
                        <div style="margin-top: 10px;">

                            {% for category in categorys %}
                            <div >
                                <!-- 主分类 -->
                                <div style="float: left;width: 100%;margin-top:20px;">
                                    <p>
                                        <span class="zhiwei">{{ category.name }}</span>
                                    </p>
                                </div>
                                <!-- 小分类 -->
                                <div style="padding-top:10px;float:left;width:100%">
                                {% for job in category.job_set.all %}
                                    {% if job.name|length <= 10 %}
                                    <div style="float: left;width:50%;margin-top: 10px;">
                                    {% else %}
                                    <div style="float: left;width:100%;margin-top: 10px;">
                                    {% endif %}
                                        <p>
                                            <span class="zizhiwei zizhiweiname" id="job{{job.id}}" onclick="choosework('{% url 'jobDesc' job.id %}', '{{job.id}}')">&gt;{{job.name}}</a></span>
                                        </p>

                                    </div>
                                {% endfor %}
                                </div>
                            </div>
                            {% endfor %}

                    </td>
                    <td style="border-left: 0px solid #000000;vertical-align: top;width: 60%">

                        <!-- 职位描述 -->
                        <div style="padding-left: 5%;text-align: left;">
                            <p>
                                <span style="font-size: 24px ;font-family: '微软雅黑 Bold', 微软雅黑 ;color: #000000;font-weight: 700">职位描述</span>
                            </p>
                            <!-- 此处div用于显示职位描述内容，后期会替代 -->
                            <div  style="text-align: left;padding-left: 3%;margin-top: 10px;">
                                <span id="job_name" style="font-size: 18px;font-family:'微软雅黑 Bold', '微软雅黑';font-weight:700;color:#000000;">系统策划</span>
                                <br><br>
                                <div>
                                    <pre id="workDetail" style="font-family:'微软雅黑 Regular', '微软雅黑';font-weight:400;font-size: 18px;line-height:40px; border:0">
                                       职能描述 
                                    </pre>
                                </div>
                            </div>

                        </div>

                    </td>
                </tr>

            </table>


        </div>

    </div>

</div>









{% endblock %}

templates/newsDetail.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <div style="text-align: center;margin-top: 5%">
        <p>
            <span style="text-align: center ;font-size: 36px;font-family: '微软雅黑 Bold', 微软雅黑">
                {{ new.title }}
            </span>
        </p>
    </div>


    <div>
        <div class="row" style="width: 90%;text-align: center;margin-left: 5%;padding-top:2%;" align="center">
            <div >
                    <img src="{% static '/images/' %}{{ new.bigpicture }}" alt="">
            </div>
        </div>
        
        <div style="text-align: left;margin-bottom: 200px;padding-top:2%;">
        
            <pre class="preword">           {{ new.content }}</pre>
        </div>
    </div>

</div>

{% endblock %}